### ISSUE TITLE
Failed to compile build

### ISSUE THREAD

**Issue by dvmac** [geops/ole3#1]
Hi there,
I've looked at the demo of this and there's some great functionality that I'd like to include in my own project. I've downloaded the zip and tried to run npm install / npm run-script build but it returns errors which I don't quite understand. I was wondering if someone could help?
I have a limited understanding of node I'm afraid but my debug log is below:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'build' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ole3@0.0.0
6 info build ole3@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info ole3@0.0.0 Failed to exec build script
9 error ole3@0.0.0 build: `node ./scripts/compile.js`
9 error Exit status 8
10 error Failed at the ole3@0.0.0 build script.
10 error This is most likely a problem with the ole3 package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./scripts/compile.js
10 error You can get their info via:
10 error     npm owner ls ole3
10 error There is likely additional logging output above.
11 error System Darwin 11.4.2
12 error command "node" "/usr/local/bin/npm" "run-script" "build"
13 error cwd /Applications/MAMP/htdocs/ole3-master
14 error node -v v0.10.32
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

Any advice would be appreciated, thanks.

**Comment by janvogt** [comment]
Hi dvmac,
thanks for your interest in using ole3. First I have to say, that this project is in a very early development state and certainly not ready for productive use. Most importantly it's API will be changed frequently and most certainly in a breaking way. Also the documentation is close to non-existent. The build process is currently used under linux and mac with node and npm installed and - though it aims to be platform independent - may not work on e.g. windows.
Having said that, if you still want to use ole3 in this early stage, you can just use the ready compiled ole3.js in the dist folder which I just added to the repo. Nevertheless, I strongly suggest at this point using more matured projects such as geops/ole for openlayers 2.

**Comment by janvogt** [comment]
I am closing this, since the compiled version is included now.
